apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nas
  labels:
    alicloud-pvname: pv-nas
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "alicloud/nas"
    options:
      server: "*************"   # NASのエンドポイント
      path: "/k8s"
      vers: "3"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      alicloud-pvname: pv-nas

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nas
  labels:
    app: nas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nas
  template:
    metadata:
      labels:
        app: nas
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - name: pvc-nas
            mountPath: "/data"
      volumes:
        - name: pvc-nas
          persistentVolumeClaim:
            claimName: pvc-nas
