 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: ingress
   annotations:
    ingress.aliyun.weight/nginx: '50'
 spec:
   backend:
     serviceName: wordpress
     servicePort: 80
   rules:
   - host: wordpress.io
     http:
       paths:
       - path: /
         backend:
           serviceName: wordpress
           servicePort: 80
       - path: /
         backend:
           serviceName: nginx
           servicePort: 80
