 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: ingress
 spec:
   rules:
   - host: bg-test.io
     http:
       paths:
       - path: /
         backend:
           serviceName: service-blue
           servicePort: 80