apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress_pvc
  labels:
    app: wordpress
    tier: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
