apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-id: "lb-e9bkb2bqa5kkyu1pah9b7"
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true" 
spec:
  type: LoadBalancer
  #loadBalancerIP: "47.245.57.68"
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
